- pkg/build/examples/typescript/nopackagejson/main.ts
- pkg/build/node.go
- pkg/build/node_test.go
Errors if no package.json because there are no package*.json or yarn.* files.
Added test to confirm fix
> Fix build when no package.json

- pkg/deploy/taskdir/definitions/def_0_3.go
This adds proper handling to the `query` property in KindOptions + SQL entrypoint contents. It also adds SetEntrypoint to Definition_0_3 & GetQuery to SQLDefinition_0_3.
Supports AIR-2461.
> Properly handle query / entrypoint contents in SQL definition

- pkg/build/builder.go
- pkg/deploy/discover/script_discover.go
- pkg/runtime/sql/sql.go
Adds a skeleton definition of SQL runtime without local execution. Also adds SQL + REST consideration to NeedsBuilding.
Resolves AIR-2485.
> Add SQL runtime

- pkg/api/client.go
- pkg/api/mock/client_mock.go
- pkg/deploy/discover/discover.go
This PR adds an `envSlug` parameter to the client API (`GetTask` and `UpdateTask`). This [will be used in the CLI](https://github.com/airplanedev/cli/pull/374) and (in a future PR) in the deployer.
cc @ameyakhare
> Add env parameter to API client

- pkg/deploy/discover/discover.go
This is used by the CLI when deploying into an environment.
I mistakenly removed it from this PR: https://github.com/airplanedev/lib/pull/38#discussion_r796807118
> Add EnvSlug to Deployer

- pkg/api/client.go
- pkg/api/mock/client_mock.go
- pkg/deploy/taskdir/definitions/def_0_3_test.go
This is dead code since tasks-as-code doesn't deal with permissions anymore.
> Remove unused List{Users,Groups} from API client interface

- pkg/build/python.go
If a `pip.conf` file is in the root, sets the `PIP_CONFIG_FILE` env var when running `pip install`. Feature request from https://app.intercom.com/a/apps/we6lj1ka/inbox/inbox/5188557/conversations/29392
---
cc @joshma
> Support pip.conf when building python tasks

- pkg/deploy/discover/discover.go
- pkg/deploy/discover/discover_test.go
Returns a single task config per slug, in order of discoverers, in order of discovery. E.g.: given discoverers [DefnDiscoverer, ScriptDiscoverer], if task `my_task` has both a linked script & a defn file, the defn file will take precedence; given two defn files for the same task, the first defn file to be discovered takes precedence.
Resolves AIR-2973.
> Handle the same task being discovered by multiple discoverers

- pkg/deploy/taskdir/definitions/def_0_3.go
Not strictly necessary, but kind of a nice-to-have. We save entrypoint in KindOptions for all other kinds requiring an entrypoint.
Resolves AIR-2975.
> Save SQL entrypoint in KindOptions

- pkg/deploy/discover/discover_test.go
- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/def_0_3_test.go
Got lost somewhere in merges & reshuffling. Workdir is now being handled through build config, not kind options.
> Remove Workdir from NodeDef03

- pkg/deploy/taskdir/definitions/error.go
- pkg/deploy/taskdir/definitions/schema_0_3.json
- pkg/deploy/taskdir/taskdef.go
This brings back `errReadDefinition` to tell users why their schema is failing.
Before:
```
Error: Invalid format: [(root): Must validate one and only one schema (oneOf) timeout: Invalid type. Expected: number, given: string (root): Must validate all the schemas (allOf)]
```
After:
```
(root): Must validate one and only one schema (oneOf)
timeout: Invalid type. Expected: number, given: string
image: image is required
(root): Must validate all the schemas (allOf)
For more information on the task definition format, see the docs:
https://docs.airplane.dev/deprecated/task-definition-reference
```
(We'll need to update the task defn link!)
The change to the schema is to pin the schema to a particular JSON schema draft, & also to put a restriction on additional properties.
Resolves AIR-3062.
> Show better schema errors

- pkg/runtime/javascript/javascript.go
- pkg/runtime/python/python.go
- pkg/runtime/runtime.go
- pkg/runtime/shell/shell.go
- pkg/runtime/sql/sql.go
Shortcut to if `PrepareRun` returns `ErrNotImplemented`.
Supports AIR-3060, AIR-3061.
> Add SupportsLocalExecution to Runtime interface

- pkg/deploy/taskdir/definitions/schema_0_3.json
Opting to remove this rather than double-implement maximums.
Resolves AIR-3136.
> Remove maximum constraint from timeout in schema

- pkg/deploy/taskdir/definitions/def_0_3.go
Confusingly, image definitions have an "entrypoint" field that is different from the "entrypoint" field for other definitions. Unlike, say, a Python definition, an image definition's entrypoint is not a script, but an instruction to Docker to override the default image entrypoint. All entrypoint-related functions on definitions & task kind definitions are of the script variety, & so technically image definitions don't have entrypoints. This is correct for `getEntrypoint()`, but was incorrect for `setEntrypoint()` & `{set,get}AbsoluteEntrypoint()`.
> Fix entrypoint for image definition

- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/def_0_3_test.go
- pkg/deploy/taskdir/definitions/schema_0_3.json
Some schema refactoring, in an effort to get the schema closer to what's on the frontend.
* Renames `image` to `docker`. (Internally we still refer to this as kind=image, so it remains ImageDefinition.)
* Moves Docker command to a string instead of a string array.
* Simplifies constraints to be a map of key -> label.
> Simplify schema

- pkg/build/versions.json
Upgrade python from buster -> (more up to date) bullseye. Use the closest version of python 3.9.4 -> 3.9.6.
This image has OpenSSL 1.1.1k  25 Mar 2021 instead of a 2019 version. 
FIXES AIR-2903
---
We determined that openssl is probably not causing any issues, but this upgrades us to a newer version.
We're skipping from d->k https://www.openssl.org/news/openssl-1.1.1-notes.html
> Switch to python 3.9.6 bullseye

- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/def_0_3_test.go
- pkg/deploy/taskdir/definitions/fixtures/docker.task.yaml
- pkg/deploy/taskdir/definitions/fixtures/node.task.yaml
- pkg/deploy/taskdir/definitions/fixtures/python.task.yaml
- pkg/deploy/taskdir/definitions/fixtures/rest.task.yaml
- pkg/deploy/taskdir/definitions/fixtures/shell.task.yaml
- pkg/deploy/taskdir/definitions/fixtures/sql.task.yaml
- pkg/deploy/taskdir/definitions/schema_0_3.json
- pkg/deploy/taskdir/definitions/yaml_templates.go
Updates schema + parameter handling for config var options. Resolves AIR-3351.
Run `airplane init` from a task with a parameter with config var options. Run `airplane deploy` on resulting definition file.
> Handle parameters with config var options

- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/fixtures/sql.task.yaml
- pkg/deploy/taskdir/definitions/schema_0_3.json
- pkg/deploy/taskdir/definitions/yaml_templates.go
New SQL tasks get created with a default TransactionMode of auto. Initializing SQL tasks without a TransactionMode results in no transactionMode entry in the definition file. Resolves AIR-2896.
Deploy a SQL task with a transaction mode. Initialize a SQL task from an existing task with a transaction mode, and without a transaction mode.
> Add TransactionMode to SQL tasks

- pkg/deploy/discover/defn_discover.go
- pkg/deploy/discover/discover_test.go
- pkg/deploy/discover/fixtures/defn.task.yaml
- pkg/deploy/discover/fixtures/defn_incorrect_entrypoint.task.yaml
Throw an error in the discovery phase if the entrypoint does not exist. Current behavior is that the deploy fails and we throw a sentry error.
Ideally we'd also not log a sentry err if one of these sneaks in. We can implement this too, but it requires integrating the error lib into lib.
Unit tested
> Err if entrypoint does not exist

- pkg/api/client.go
- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/def_0_3_test.go
- pkg/deploy/taskdir/definitions/fixtures/rest.task.yaml
- pkg/deploy/taskdir/definitions/fixtures/sql.task.yaml
- pkg/deploy/taskdir/definitions/schema_0_3.json
- pkg/deploy/taskdir/definitions/yaml_templates.go
- pkg/runtime/typescript/typescript.go
This PR adds a `Configs` field to the task definition YAML for REST and SQL tasks, similar to how there is an `EnvVars` field for code tasks. It also adds a `Configs` field to a couple structs so that the CLI can deploy a task with config attachments. 
Unit tests
> Add configs to task definition yaml

- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/def_0_3_test.go
- pkg/deploy/taskdir/definitions/interface.go
We need to be able to get a definition's config attachments in order for the CLI to check that the config variables exist - this PR adds a method to the definition interface to do that.
Unit tests
> Expose config attachments from definition

- pkg/outputs/parse.go
- pkg/outputs/parse_test.go
Part of better OOM handling - agents will use this to filter out output lines which are too long.
Unit tests
> Add max output line option to output parsing

- pkg/api/client.go
- pkg/build/types.go
- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/def_0_3_test.go
- pkg/deploy/taskdir/definitions/schema_0_3.json
This change adds support for a top-level `runtime` field in task configs. This will be used to indicate durability, among other use cases. See https://github.com/airplanedev/airport/pull/2147 for the associated airport-side changes.
cc: @colinking @calufornia 
Testing completed successfully via building the cli with this revision and doing some deploys to verify that nothing bad happened.
> Add optional runtime field in task configs

- pkg/api/client.go
- pkg/api/mock/client_mock.go
- pkg/deploy/discover/defn_discover.go
- pkg/deploy/discover/discover_test.go
- pkg/deploy/discover/script_discover.go
Skip discovering archived tasks. Print a warning to the console.
Unit tested
FIXES https://linear.app/airplane/issue/AIR-3596/archived-task-should-gracefully-error-when-deploying
> Skip archived tasks

- .github/CONTRIBUTING.md
- pkg/build/versions.json
- pkg/deploy/taskdir/definitions/fixtures/node.task.yaml
- pkg/deploy/taskdir/definitions/schema_0_3.json
- pkg/deploy/taskdir/definitions/yaml_templates.go
We plan on adding support for node v18, per https://linear.app/airplane/issue/AIR-3549/support-node-18. This PR adds the latest v18 buster image to `versions.json` so that we can start building images with it.
Resolves AIR-3549
n/a
> Add support for Node v18

- .github/workflows/sourcegraph.yml
Upgrade sourcegraph lsif gh action which fixes sourcegraph with go 1.18
> Upgrade sourcegraph

- pkg/build/durable/worker-and-activity-shim.js
- pkg/build/node.go
This change updates our durable node shim to set an authentication token and use TLS when communicating with the Temporal API. The token parts rely on a just-released update to the Temporal Node SDK, so we also need to bump the version of the latter.
Testing completed successfully building an image locally and running it along with the changes in https://github.com/airplanedev/airport/pull/2326.
> Use authentication and TLS for temporal communication in node shim

- pkg/api/client.go
- pkg/deploy/discover/discover.go
- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/def_0_3_test.go
- pkg/deploy/taskdir/definitions/interface.go
- pkg/deploy/taskdir/definitions/schema_0_3.json
Resolves AIR-3725
Parses schedules from task defn files and exposes them on DefinitionInterface to be used by the CLI and api when deploying.
def_0_3_test.go:TestDefinitionMarshal_0_3
def_0_3_test.go:TestDefinitionGetSchedules_0_3
> Parse schedules from yaml/json task defns

- pkg/api/client.go
- pkg/api/triggers.go
- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/def_0_3_test.go
We want to be able to parse triggers to populate the schedules in the task definition file. This diff exports a subset of the pkg/ap/triggers from airport to lib and then uses those to parse triggers fetched from the api into the task definition file
Schedules parse correctly in the cli/are added to the task defn file when initializing a task from an existing slug
> Add method to parse api triggers into task definition

- pkg/deploy/taskdir/definitions/def_0_3.go
I noticed this when making some changes for resource encryption - we define a mapping from name -> resource, populate it with the result of `/resources/list`, but then don't do anything with this map. This removes the unnecessary API call to list resources.
Tested a CLI deploy of a SQL task just to be sure, but this change should be safe since we're just removing unused code.
> Remove unnecessary call to list resources

- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/fixtures/docker.task.yaml
- pkg/deploy/taskdir/definitions/fixtures/shell.task.yaml
- pkg/deploy/taskdir/definitions/yaml_templates.go
We include this information in our docs and when configuring params in the UI, but it is also nice to include it in the initial tasks as code for those not using the UI
Integration tests that test the output yaml file.
FIXES AIR-3899
> Include info in initial task about param usage

- pkg/build/node.go
- pkg/build/workflow/worker-and-activity-shim.js
- pkg/utils/fsx/fsx.go
- pkg/utils/fsx/fsx_test.go
Right now, we assume that a task's custom activities exist in a file called `activities.ts` or `activities.js` at the root of their project. However, a task may not have custom activities (if it is purely using the Node SDK) - this PR makes it so that we don't encounter an import error if neither of these files exist by creating an empty `activities.js` file, similar to how we create an empty `package.json` if the task does not contain one. The activities that are registered with the worker is the union of the activities exported by the Node SDK and the task's custom activities.
cc @colinking @yolken-airplane 
Resolves AIR-3973
Tested locally by deploying and running a task with & without `activities.ts`.
> Make custom Temporal activities optional

- pkg/build/workflow/worker-and-activity-shim.js
- pkg/build/workflow/workflow-shim-activities.js
- pkg/build/workflow/workflow-shim.js
This PR reads from the airplane args object set when the workflow is started by the API to populate the env vars that we'll monkey patch into the Temporal workflow's `process.env`. After this, the SDK should have the env vars it needs to properly execute tasks, and user-defined env vars should work.
Tested locally by running a workflow task with custom env vars, and also verified the airplane-internal env vars were populated into `process.env`.
> Read env var data from airplane args

- pkg/build/workflow/workflow-shim-activities.js
- pkg/build/workflow/workflow-shim.js
See: https://airplanedev.slack.com/archives/C038E9488F5/p1656710043454659?thread_ts=1656709429.747769&cid=C038E9488F5
API changed here: https://github.com/airplanedev/airport/pull/2698/files
Run workflow locally, confirm env vars are still passed through.
> Rename TaskRevisionEnvVarNames to EnvVarNames

- pkg/build/workflow/workflow-shim.js
If a workflow fails (returns an error), we should log the error so the runbroker can interpret it and mark the run as failed. The previous behavior, which throws the error again, causes temporal to retry indefinitely.
Tested this locally with a runbroker change for both a task that has an activity and one that's only a workflow execution
> AIR-3982 Support failed workflows

- pkg/build/view.go
Ran into this bug during the internal alpha, this fixes CORS errors when trying to run tasks in deployed views
Deployed a view locally that runs a task, makes sure it works
---
cc @stepzhou @leeweisberger
> Use correct API host when building

- pkg/build/views/index.html
The Inter font package is too large. The inter package dependency is getting removed in https://github.com/airplanedev/views/pull/86
Rather than downloading it, add a link to the hosted font
Resolves AIR-4255
Not sure how to build the edited lib with CLI
> Add Inter font link

- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/fixtures/specialchars.task.yaml
- pkg/deploy/taskdir/definitions/yaml_templates_test.go
This only really needs to be done for name, as it's one of the few freeform fields that folks get when initializing a task. (Entrypoint is the other one, but not sticking to ascii characters for entrypoints seems like asking for trouble. Willing to punt on this.)
Resolves AIR-4252.
Unit tests.
> Ensure name is valid YAML

- pkg/build/node.go
I've noticed that when deploying some workflow tasks, the image size is very large (~1.9GB), which causes pushing to artifact registry to take a significant amount of time. Most of the size seems to come from the yarn cache:
```
root@5a2283c9cd08:/usr/local/share/.cache# du -sh yarn
1.5G	yarn
```
Unfortunately, yarn doesn't seem to have an option to not use a cache in the first place, and so the best we can do is remove it in the same RUN instruction that we install the packages in.
Tested by deploying a task with the cli pointing to a local version of lib, and verifying that the size of the resulting image was reduced (~1.9GB -> 450MB).
> Clear yarn cache after installing

- pkg/outputs/parse.go
- pkg/outputs/parse_test.go
This change updates the lib `Parse` function to include the size of each log line in its response. This will be used for imposing output size limits in the agent v2 runbroker.
cc: @zhan-airplane 
Testing completed successfully via unit tests.
> Add size data into parsed lines

- pkg/deploy/taskdir/definitions/def_0_3.go
- pkg/deploy/taskdir/definitions/def_0_3_test.go
- pkg/deploy/taskdir/definitions/schema_0_3.json
Resource attachments can now be specified as a list, where each element is either a resource slug (where alias = slug) or an object with a single key (where key = alias, value = slug).
```
resources:
- httpbin
- db: demo_db
```
When running `airplane init`, resource attachments are preferred as a mapping of alias -> slug.
```
resources:
httpbin: httpbin
db: demo_db
```
Unit tests, tested manually.
> Allow resources to be a list
